### ISSUE TITLE
Project TODO

### ISSUE THREAD

**Issue by ghost** [parsecsv/parsecsv-for-php#2]
In no particular order, my thoughts on getting this library up to date for some well deserved showtime!
- [x] Code Cleanup and new style documentation (done: 4b28088)
- [x] Composer Support (done: 5a70a7b)
- [x] Proper access for protected methods and properties
- [ ] PHP 5.3 standardization
- [ ] Unit TEST(S)!!! :rage:  :sob: :relieved: (#4)
- [x] Contributors section in Readme (done: f59af53)
- [x] Update readme (grammar and maintenance notice) (done: c915579)
- [ ] Update Changelog
